### ISSUE TITLE
Support ERC165?

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/ERC875-Example-Implementation#3]
https://github.com/ethereum/EIPs/blob/master/EIPS/eip-165.md

**Comment by colourful-land** [comment]
It surely makes sense imho. Does ERC875 need to explicitly say that it supports 165, or is it inexplicit?

**Comment by miang719** [comment]
@hboon anyone u need to assign the task?

**Comment by hboon** [comment]
@miang719 I suppose @James-Sangalli.

So ERC165 is easy to support and we can and I think we should.

---

There's room for something better, maybe as a separate issue. As a wallet app, we tend to work with all kinds of tokens, so this is quite relevant to us. How feasible is it to just flip the check around, instead of querying by calling a function like `supportsInterface("0x80ac58cd")`, can't we just implement a function to return the entire list of public functions?:

    string[] public funs;

    constructor () public {
        funs = [
            "balanceOf(address)",
            "ownerOf(uint256)",
            "safeTransferFrom(address,address,uint256,bytes)",
            //List every public function
        ];
    }

    function supportedFunctions() public view returns (string[]) {
        return funs;
    }

ERC165 is easy to implement wrongly (outdated hash, wrong hash), support for optional interfaces/functions is ambiguous and doesn't support querying for a subset of an interface or a specific function. On the other hand, a single function that returns everything that is supported seems so much better.

**Comment by James-Sangalli** [comment]
Added but not implemented, can make it optional for whatever token standard
